# Generated by Django 3.0.1 on 2020-01-03 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200103_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookauthor',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to='api.Book'),
        ),
    ]
