# Generated by Django 3.0.1 on 2020-01-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20200107_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookauthor',
            name='position_in_series',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
