# Generated by Django 3.0.1 on 2020-01-16 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20200113_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='current_status',
            field=models.CharField(choices=[('WTF', 'Want to Read'), ('CURR', 'Currently Reading'), ('COMP', 'Completed'), ('PAUS', 'Paused'), ('DNF', 'Discarded')], default='WTF', max_length=4),
        ),
    ]
