# Generated by Django 3.0.1 on 2020-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_book_current_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='current_status',
            field=models.CharField(choices=[('WTR', 'Want to Read'), ('CURR', 'Currently Reading'), ('COMP', 'Completed'), ('PAUS', 'Paused'), ('DNF', 'Discarded')], default='WTR', max_length=4),
        ),
    ]
